# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 07:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
